# serializers.py
from rest_framework import serializers
from django.contrib.auth import get_user_model
from django.conf import settings
from django.utils import timezone
from datetime import timedelta
import random
import string
from .models import OTP
from .utils import validate_and_get_otp
from .messages import AuthMessages

User = get_user_model()

class SignupSerializer(serializers.Serializer):
    email = serializers.EmailField()
    # name = serializers.CharField(max_length=150)
    password = serializers.CharField(
        write_only=True,
        min_length=8,
            error_messages={
                "min_length": "Password must be at least 8 characters long."
            }
        )
    referral_code = serializers.CharField(max_length=20, required=False, allow_blank=True)
    
    def validate_email(self, value):
        value = value.lower().strip()#makes email lowercase and removes spaces.
        verified_user = User.objects.filter(email=value, verified=True).exists()#.filter() returns a QuerySet, not a True/False value.
        #.exists() is used to check if any record matches (returns True or False).

        if verified_user:
            raise serializers.ValidationError("This email is already registered.")
        return value
    
    # def validate_name(self, value):
    #     return value.strip()
    
    def create(self, validated_data):
        email = validated_data['email']
        
        # It removes old unverified accounts with the same email before creating a new one.
        User.objects.filter(email=email, verified=False).delete()
        
        # Create new user
        user = User.objects.create_user(
            username=email,
            email=email,
            # first_name=validated_data['name'],
            password=validated_data['password'],
            referral_code=validated_data.get('referral_code') or None,
            verified=False
        )
        
        # Generate and send OTP
        otp_code = ''.join(random.choices(string.digits, k=6))
        '''
        Generates a 6-digit random OTP made of numbers.
        string.digits = '0123456789'
        random.choices(..., k=6) → picks 6 random digits.
        .join(...) → combines them into a single string like '483920'.
        '''
        expires_at = timezone.now() + timedelta(minutes=10)

        #Deletes any previous unused OTPs for that email before sending a new on
        OTP.objects.filter(email=email, is_used=False).delete()
        OTP.objects.create(
            email=email,
            otp_code=otp_code,
            expires_at=expires_at
        )
        
        self.send_otp_email(email, otp_code)
        
        return user
    
    
    '''
    ❓From where this 'validated_data' comes in the line def create(self, validated_data)?
    Ans:
    When DRF serializer’s .is_valid() runs successfully, it stores cleaned input data in validated_data.
    DRF automatically passes this dictionary into the create() method when .save() is called.
    👉 In short: validated_data = all the valid fields from the user’s request (after passing validation).
    
    '''


    '''
    ❓Why @staticmethod for send_otp_email?
    Ans:
    @staticmethod: Means the method doesn't need access to self (the serializer instance),or any instance data. It's a utility function that can work independently
    Use case: The method only uses the parameters passed to it (email and otp_code)

    ❓why I can use a independant function like send_otp_email in this case

    🔴email and otp_code are generated by your system inside the create() method — not sent by the user.
    🔴Since send_otp_email() just uses those values to send an email, it doesn’t need anything from the serializer instance (self).
    🔴That’s why it can be a @staticmethod — it works independently of the serializer object.
    '''
    @staticmethod
    def send_otp_email(email, otp_code):
        import resend

        resend.api_key = settings.RESEND_API_KEY

        html_body = f"""
        <div style="font-family: Arial, sans-serif; max-width: 480px; margin: auto; padding: 24px; border: 1px solid #e0e0e0; border-radius: 8px;">
            <h2 style="color: #2d2d2d;">Your Verification Code</h2>
            <p style="color: #555;">Dear User,</p>
            <p style="color: #555;">Thank you for registering with <strong>Quiz Question AI</strong>.</p>
            <p style="color: #555;">Your One-Time Password (OTP) for email verification is:</p>
            <div style="text-align: center; margin: 24px 0;">
                <span style="font-size: 36px; font-weight: bold; letter-spacing: 8px; color: #4f46e5;">{otp_code}</span>
            </div>
            <p style="color: #555;">This code is valid for <strong>10 minutes</strong>. Please do not share it with anyone.</p>
            <p style="color: #555;">If you did not create an account, please ignore this email or contact our support team immediately.</p>
            <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 24px 0;" />
            <p style="color: #999; font-size: 12px;">Best regards,<br/>The Quiz Question AI Team<br/>support@quizquestionai.com</p>
        </div>
        """

        plain_text = f"""Dear User,

Thank you for registering with Quiz Question AI app.

Your One-Time Password (OTP) for email verification is:

        {otp_code}

This code is valid for 10 minutes. Please do not share it with anyone for security reasons.

If you did not create an account, please ignore this email or contact our support team immediately.

Best regards,
The Quiz Question AI App Team
support@quizquestionai.com"""

        import requests
        import logging
        logger = logging.getLogger(__name__)
        
        try:
            response = requests.post(
                "https://api.resend.com/emails",
                headers={
                    "Authorization": f"Bearer {settings.RESEND_API_KEY}",
                    "Content-Type": "application/json"
                },
                json={
                    "from": settings.RESEND_FROM_EMAIL,
                    "to": [email],
                    "subject": "Your Verification Code",
                    "html": html_body,
                    "text": plain_text,
                },
                timeout=5  # 5 seconds timeout to prevent hanging the worker
            )
            response.raise_for_status()
        except Exception as e:
            logger.error(f"Failed to send OTP email via Resend: {str(e)}")
            if hasattr(e, 'response') and getattr(e, 'response') is not None:
                logger.error(f"Resend API response: {e.response.text}")


class VerifyOTPSerializer(serializers.Serializer):
    email = serializers.EmailField()
    otp_code = serializers.CharField(max_length=6)
    
    def validate(self, data):
        email = data['email'].lower().strip()
        otp_code = data['otp_code'].strip()
        
        # try:
        #     otp = OTP.objects.filter(email=email, is_used=False).latest('created_at')
        # except OTP.DoesNotExist:
        #     raise serializers.ValidationError("No valid OTP found for this email.")
        
        # if not otp.is_valid():
        #     raise serializers.ValidationError("OTP has expired.")
        
        # if otp.otp_code != otp_code:
        #     raise serializers.ValidationError("Invalid OTP code.")
        otp = validate_and_get_otp(email, otp_code)  # 👈 call the function here

        data['otp'] = otp
        return data


class ResendOTPSerializer(serializers.Serializer):
    email = serializers.EmailField()
    
    def validate_email(self, value):
        value = value.lower().strip()
        user = User.objects.filter(email=value, verified=False).exists()
        if not user:
            raise serializers.ValidationError("This email is already verified")
        return value


class LoginSerializer(serializers.Serializer):
    email = serializers.EmailField()
    password = serializers.CharField(write_only=True)
    
    def validate(self, data):
        email = data['email'].lower().strip()
        password = data['password']
        
        try:
            user = User.objects.get(email=email, verified=True)
        except User.DoesNotExist:
            raise serializers.ValidationError("No account found with this email.")
        
        if not user.check_password(password):#if the password enterd by the user is not correct 
            raise serializers.ValidationError("Incorrect password. Please try again.")
        
        data['user'] = user
        return data


class ForgotPasswordSerializer(serializers.Serializer):
    email = serializers.EmailField()
    
    def validate_email(self, value):
        value = value.lower().strip()
        user = User.objects.filter(email=value, verified=True).exists()
        if not user:
            raise serializers.ValidationError("No account found with this email.")
        return value


class ResetPasswordSerializer(serializers.Serializer):
    # email = serializers.EmailField()
    # otp_code = serializers.CharField(max_length=6)
    new_password = serializers.CharField(write_only=True, min_length=8)
    
    # def validate(self, data):
    #     email = data['email'].lower().strip()
    #     otp_code = data['otp_code'].strip()
        
    #     # try:
    #     #     otp = OTP.objects.filter(email=email, is_used=False).latest('created_at')
    #     # except OTP.DoesNotExist:
    #     #     raise serializers.ValidationError("No valid OTP found for this email.")
        
    #     # if not otp.is_valid():
    #     #     raise serializers.ValidationError("OTP has expired.")
        
    #     # if otp.otp_code != otp_code:
    #     #     raise serializers.ValidationError("Invalid OTP code.")
    #     otp = validate_and_get_otp(email, otp_code)  # 👈 call the function here      
    #     data['otp'] = otp
    #     return data


















